name: custom_webview
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  flutter_pdfview: ^1.3.2
  webview_flutter_wkwebview: ^3.9.4
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
